stages:
  - copy
  - build

Copy app:
  stage: copy
  script:
    - cd ..
    - cp -rf $(pwd)/*  /home/gitlab-runner/tell-me/
    - cd /home/gitlab-runner/tell-me/
    - docker-compose down
  only:
    - master
  tags:
    - bash-bikespot


Build app:
  stage: build
  script:
    - cd /home/gitlab-runner/tell-me
    - docker-compose build
    - cp /home/gitlab-runner/config.json /home/gitlab-runner/tell-me/
  only:
    - master
  tags:
    - bash-bikespot
