stages:
  - copy
  - build

job-api:
  stage: copy
  script:
    - cd ..
    - cp -rf tell-me  /home/gitlab-runner/
    - cd /home/gitlab-runner/tell-me
    - docker-compose down
  stage: build
  script:
    - cd /home/gitlab-runner/tell-me
    - docker-compose build
    - cp /home/gitlab-runner/config.json /home/gitlab-runner/tell-me/
  only:
    - master
  tags:
    - bash-bikespot

